push

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,16 +1,68 @@
 #!/usr/bin/env bash
+# duplicate web-01 to web-02
 
-# Update and install nginx
-sudo apt-get -y update
-sudo apt-get -y install nginx
+echo -e "Updating and doing some minor checks...\n"
 
-# Extract the relevant part of the hostname (assuming the hostname is in the format 03-web-01, 03-web-02, etc.)
-HOSTNAME=$(hostname)
-CUSTOM_HEADER_VALUE=$(echo "$HOSTNAME" | sed -r 's/^03+-(web-[0-9]+)/\1/')
+function install() {
+        command -v "$1" &> /dev/null
 
-# Add the custom header configuration
-sudo sed -i '/^\s*server_name.*/a \        add_header X-Served-By '"$CUSTOM_HEADER_VALUE"';' /etc/nginx/sites-available/default
+        if [ $? -ne 0 ]; then
+                echo -e "       Installing: $1$\n"
+                sudo apt-get update -y -qq && \
+                        sudo apt-get install -y "$1" -qq
+                echo -e "\n"
+        else
+                echo -e "       ${1} is already installed.\n"
+        fi
+}
 
-# Restart nginx to apply changes
-sudo systemctl restart nginx
+install nginx
 
+echo -e "\nSetting up some minor stuff.\n"
+
+sudo ufw allow 'Nginx HTTP'
+if [ -d "/var/www" ]; then
+        sudo chown -R "$USER":"$USER" /var/www
+        sudo chmod -R 755 /var/www
+else
+        sudo mkdir -p /var/www
+        sudo chown -R "$USER":"$USER" /var/www
+        sudo chmod -R 755 /var/www
+fi
+
+for dir in /var/www/{html,error}; do
+        if ! [ -d "$dir" ]; then
+                mkdir -p "$dir"
+        fi
+done
+
+echo "Hello World!" > /var/www/html/index.html
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+                listen 80 default_server;
+                listen [::]:80 default_server;
+                root /var/www/html;
+                index index.html index.htm index.nginx-debian.html
+                server_name_;
+                add_header X-Served-By \$hostname;
+                location / {
+                        try_files \$uri \$uri/ =404;
+                }
+                if (\$request_filename ~ redirect_me){
+                        rewrite ^ https://th3-gr00t.tk/ permanent;
+                }
+                error_page 404 /error_404.html;
+                location = /error_404.html {
+                        internal;
+                }
+}"
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+        sudo service nginx start
+else
+        sudo service nginx restart
+fi
